adding code and updated docs/readme
adafruit/Adafruit_CircuitPython_VCNL4020 pull request #1
Opened 2023-10-23 15:55 UTC by BlitzCityDIY

Adding library, example and docs/readme.

2023-10-24 16:19 UTC, BlitzCityDIY commented
in thinking about what limor said in the internal meeting yesterday about enums, i'm wondering if i should property-ify a few of the parameter-setters, rather than having them just be RWBits, so that we can check for correct values

2023-10-24 19:05 UTC, tannewt requested changes
I wouldn't use ENUM-like things because the variable names are pretty large in memory. Instead, I'd do the list of valid numbers approach for PROX_RATE, AMBIENT_RATE and PROX_FREQ. So the properties would just take in a number and validate against the list. AVG_SAMPLES and INT_COUNT can also take in an int and verify it is a power of two between the valid range.

The property doc can explain the valid numeric values and the units.

2023-10-24 19:05 UTC, tannewt commented on adafruit_vcnl4020.py
> +        return (self._command_reg >> 5) & 0x01
This is what a ROBit will do. You can use that instead.

2023-10-24 19:05 UTC, tannewt commented on adafruit_vcnl4020.py
> +        self._continuous_conversion_bit = enable
This is also what ROBit does. It gets and sets a single bit based on a bool. https://github.com/adafruit/Adafruit_CircuitPython_Register/blob/main/adafruit_register/i2c_bit.py

2023-10-30 13:30 UTC, BlitzCityDIY commented
this PR has been acting funky since friday and isn't showing my recent commit, despite a few attempts at pushing. going to close and reopen to see if that pushes it

2023-10-30 13:30 UTC, closed without merging